<#
.SYNOPSIS
Regenerate complexsurface.recon.ps.h from complexsurface.recon.ps.hlsl.

.DESCRIPTION
The world pixel shaders are stored as DWORD arrays, so the reconstruction variants have to be compiled
offline and checked in. This runs fxc over every entry point in the .hlsl and blobify.ps1 over each result,
then writes the header the driver includes.

It also refuses any shader whose compiled form contains a def instruction. A literal constant on this target
has nowhere to live but a constant register, and the compiler claims the lowest one it believes free: c1,
which the driver keeps its own data in. The .hlsl is written to leave no literals, and this catches an edit
that reintroduces one.

.PARAMETER Fxc
Path to fxc.exe. Located under the Windows SDK if not given.
#>
[CmdletBinding()]
param(
    [string] $Fxc
)

$ErrorActionPreference = 'Stop'

$sourceName = 'complexsurface.recon.ps.hlsl'
$headerName = 'complexsurface.recon.ps.h'

# Entry point in the .hlsl, and the name its compiled form is stored under. The names say which layers are
# reconstructed, since that is what distinguishes variants the layer flags alone cannot tell apart: a single
# modulated layer is a lightmap on one of these and a macro texture on the other.
$shaders = @(
    @{ Entry = 'PS_DualModulatedLight';          Name = 'g_fpComplexSurfaceDualTextureLightRecon' },
    @{ Entry = 'PS_TripleModulatedLight';        Name = 'g_fpComplexSurfaceTripleTextureLightRecon' },
    @{ Entry = 'PS_SingleWithFog';               Name = 'g_fpComplexSurfaceSingleTextureFogRecon' },
    @{ Entry = 'PS_DualModulatedLightWithFog';   Name = 'g_fpComplexSurfaceDualTextureLightFogRecon' },
    @{ Entry = 'PS_DualModulatedMacroWithFog';   Name = 'g_fpComplexSurfaceDualTextureMacroFogRecon' },
    @{ Entry = 'PS_TripleModulatedLightWithFog'; Name = 'g_fpComplexSurfaceTripleTextureLightFogRecon' },
    @{ Entry = 'PS_DualModulatedLightAndDetail'; Name = 'g_fpComplexSurfaceDualTextureLightDetailRecon' },
    @{ Entry = 'PS_DualModulatedLightAndDetailTwoLayer'; Name = 'g_fpComplexSurfaceDualTextureLightDetailTwoLayerRecon' }
)

function Find-Fxc {
    if ($Fxc) { return $Fxc }

    $roots = @(
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin",
        "$env:ProgramFiles\Windows Kits\10\bin"
    )
    foreach ($root in $roots) {
        if (-not (Test-Path $root)) { continue }
        $candidates = Get-ChildItem -Path $root -Directory -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -match '^10\.' } |
            Sort-Object Name -Descending
        foreach ($c in $candidates) {
            $exe = Join-Path $c.FullName 'x86\fxc.exe'
            if (Test-Path $exe) { return $exe }
        }
    }
    throw 'Could not find fxc.exe. Pass -Fxc with a path to it.'
}

$fxcPath = Find-Fxc
$sourcePath = Join-Path $PSScriptRoot $sourceName
$headerPath = Join-Path $PSScriptRoot $headerName
$blobify = Join-Path $PSScriptRoot 'blobify.ps1'

Write-Host "fxc: $fxcPath"

$out = New-Object System.Text.StringBuilder
$out.AppendLine("//Generated by regen-recon-shaders.ps1 from $sourceName. Do not edit by hand.") | Out-Null
$out.AppendLine('//') | Out-Null
$out.AppendLine('//The complex surface combiners for ReduceBanding, which reconstruct the lightmap and the fog map with') | Out-Null
$out.AppendLine('//a cubic B-spline and dither them by one source code instead of sampling bilinearly. Each is the') | Out-Null
$out.AppendLine('//twin of a hand written combiner and implements the same one.') | Out-Null
$out.AppendLine('//') | Out-Null
$out.AppendLine('//These read pixel shader constants c7 to c14.') | Out-Null
$out.AppendLine() | Out-Null
# These are definitions, not declarations: including this file twice would define them twice.
# They are extern, not static: a const object at namespace scope has internal linkage unless it
# says otherwise, and Shaders/ShaderLoad.cpp is what loads them.
$out.AppendLine('#pragma once') | Out-Null
$out.AppendLine() | Out-Null

# Temporaries land beside the header; the finally block below removes them.
$fxo = Join-Path $PSScriptRoot 'recon.tmp.fxo'
$asm = Join-Path $PSScriptRoot 'recon.tmp.asm'

try {
    foreach ($shader in $shaders) {
        # No /Ges: strict mode rejects the sampler2D declarations and tex2D calls this target needs, since
        # both are the pre-SM4 spelling it deprecates. There is no SM4 spelling that compiles to ps_3_0.
        $output = & $fxcPath '/nologo' '/T' 'ps_3_0' '/E' $shader.Entry '/O3' '/Fo' $fxo '/Fc' $asm $sourcePath 2>&1
        if ($LASTEXITCODE -ne 0) {
            $output | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
            throw "fxc failed on $($shader.Entry)"
        }

        $defs = Select-String -Path $asm -Pattern '^\s*def\s' | ForEach-Object { $_.Line.Trim() }
        if ($defs) {
            $defs | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
            throw "$($shader.Entry) compiled to a def instruction; see the note at the top of $sourceName"
        }

        $slots = (Select-String -Path $asm -Pattern 'instruction slots used').Line.Trim() -replace '^//\s*', ''
        Write-Host ("  ok    {0,-46} {1}" -f $shader.Entry, $slots)

        $blob = & $blobify -Path $fxo -Name $shader.Name
        $out.AppendLine($blob.TrimEnd()) | Out-Null
        $out.AppendLine() | Out-Null
    }
}
finally {
    Remove-Item $fxo, $asm -ErrorAction SilentlyContinue
}

# CRLF, matching the rest of the tree, and no trailing blank line beyond the last blob's.
[System.IO.File]::WriteAllText($headerPath, ($out.ToString() -replace "`r?`n", "`r`n"))
Write-Host ''
Write-Host "Wrote $headerPath" -ForegroundColor Green
