#pragma once

static const FLOAT UTGLR_MOVER_POLY_OFFSET_UNITS = 4.0f;
static const FLOAT UTGLR_MOVER_POLY_OFFSET_FACTOR = 1.0f;

static const FLOAT UTGLR_DETAIL_POLY_OFFSET_UNITS = 1.0f;
static const FLOAT UTGLR_DETAIL_POLY_OFFSET_FACTOR = 1.0f;
